### ISSUE TITLE
helm repo not able to get chart from jetstack.io

### ISSUE THREAD

**Issue by ranzanici** [unfor19/kubernetes-localdev#10]
I'm new to helm, but I think adding cert-manager repo to helm should be

helm repo add cert-manager https://charts.jetstack.io

also, https://charts.jetstack.io seems to provide no chart when running 'helm repo update'

**Comment by unfor19** [comment]
@ranzanici Thank you for your input. To be on the safe side, you're saying that this command - 
```
helm repo add jetstack https://charts.jetstack.io              && \
helm repo update                                               && \
kubectl apply -f cert-manager/cert-manager-crds-1.2.0.yaml     && \
helm upgrade --install --wait cert-manager jetstack/cert-manager --namespace cert-manager --version v1.2.0
```

Doesn't work?

**Comment by ranzanici** [comment]
correct, seems helm is not able to get anything from charts.jetstack.io

PROMPT: helm repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories
PROMPT: helm repo list
NAME            URL
ingress-nginx   https://kubernetes.github.io/ingress-nginx
jetstack        https://charts.jetstack.io
PROMPT: helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository

**Comment by unfor19** [comment]
Could you share the exact output after running the exact command?

```
helm repo add jetstack https://charts.jetstack.io              && \
helm repo update                                               && \
kubectl apply -f cert-manager/cert-manager-crds-1.2.0.yaml     && \
helm upgrade --install --wait cert-manager jetstack/cert-manager --namespace cert-manager --version v1.2.0
```

I can't solve it without seeing error messages / logs

**Comment by ranzanici** [comment]
sorry, my fault, it works
