### ISSUE TITLE
Problem starting minikube

### ISSUE THREAD

**Issue by mwoodpatrick** [unfor19/kubernetes-localdev#13]
When I installed minikube it installed as version v1.25.2 when I run

minikube start --driver=docker

I get following any suggestions on fix would be most appreciated

> stderr:
>         [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
>         [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
>         [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
> error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA")
> To see the stack trace of this error execute with --v=5 or higher
>

**Comment by unfor19** [comment]
Hi @mwoodpatrick , can you try removing minikube, and install v1.21.0 ? I had issues with the latest version, and 1.21.0 is the "latest working" one

**Comment by mwoodpatrick** [comment]
Many thanks for the information much appreciated. 

Running 

minikube start --apiserver-ips=<host_ip_addr>

With v1.25.2 fixed the problem I reported above

**Comment by unfor19** [comment]
@mwoodpatrick 
Excellent! Thank you for your input, closing this issue

Feel free to re-open it if you have issues with minikube
