### ISSUE TITLE
wrong wsl mount point for caroot

### ISSUE THREAD

**Issue by ranzanici** [unfor19/kubernetes-localdev#9]
when linking caroot between WSL and Windows, CAROOT_DIR should be /mnt/caroot since /mnt/media does not exist

**Comment by unfor19** [comment]
I might have created `mkdir -p /mnt/media` in the past, so I assumed it already exists.
Thanks for the catch, I'll check it out and update the course accordingly

**Comment by unfor19** [comment]
@ranzanici Thanks again for raising this issue. As explained in the PR #11  description

> WSL2: Removed `media` from `/mnt/media/caroot`, so now it's `/mnt/caroot`
